---
# configure_etc_resolv_conf/tasks/main.yml

- name: "Load variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution }}.yml"
    - "vars_{{ ansible_os_family }}.yml"

- name: 'Set TRUNCATE_NAMESERVER_LIST_AFTER_LOOPBACK_ADDRESS in /etc/default/resolvconf'
  ansible.builtin.lineinfile:
    path: '/etc/default/resolvconf'
    regex: '^TRUNCATE_NAMESERVER_LIST_AFTER_LOOPBACK_ADDRESS'
    line: 'TRUNCATE_NAMESERVER_LIST_AFTER_LOOPBACK_ADDRESS="no"'
    create: 'true'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: 'ansible_distribution == "Debian"'
  notify:
    - 'Restart network service'

- name: 'Override domainname and add 127.0.0.1 as nameserver in dhclient.conf'
  ansible.builtin.blockinfile:
    path: "{{ path_to_dhclient_conf }}"
    block: |
      interface "{{ ansible_default_ipv4.interface }}" {
        prepend domain-name-servers 127.0.0.1;
        supersede domain-name "{{ desired_domain_name }}";
        supersede domain-search "{{ desired_domain_name }}";
      }
  when: 'use_localhost_as_nameserver | bool'
  notify:
    - 'Restart network service'

- name: 'Override domainname in dhclient.conf'
  ansible.builtin.blockinfile:
    path: "{{ path_to_dhclient_conf }}"
    block: |
      interface "{{ ansible_default_ipv4.interface }}" {
        supersede domain-name "{{ desired_domain_name }}";
        supersede domain-search "{{ desired_domain_name }}";
      }
  when: 'not use_localhost_as_nameserver | bool and not custom_nameservers is defined'
  notify:
    - 'Restart network service'

- name: 'Override domainname and add custom nameservers in dhclient.conf'
  ansible.builtin.blockinfile:
    path: "{{ path_to_dhclient_conf }}"
    block: |
      interface "{{ ansible_default_ipv4.interface }}" {
        supersede domain-name-servers {{ custom_nameservers | join(", ") }};
        supersede domain-name "{{ desired_domain_name }}";
        supersede domain-search "{{ desired_domain_name }}";
      }
  when: 'not use_localhost_as_nameserver | bool and custom_nameservers is defined'
  notify:
    - 'Restart network service'
